#!/bin/sh

set -e

BASEDIR=$PWD
cd $BASEDIR
mkdir -p /opt/sersorsProject/bmp280-knot-agent
cp -r . /opt/sersorsProject/bmp280-knot-agent
cd /opt/sersorsProject/bmp280-knot-agent

echo "=> Installing libgpiod2...\n"
apt install -y libgpiod2

echo "=> Installing bmp280 requirements...\n"
pip3 install -r requirements.txt

echo "=> Installing bmp280 service...\n"
cp bmp280.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable bmp280.service
systemctl start bmp280.service

cd $BASEDIR

echo "bmp280 installed.\n"